### PR TITLE
fix: support nested classes or interfaces

### LINKED ISSUE #28: Support nested interfaces

### PR DESCRIPTION
**Pull request by vbreuss**
This PR adds support for nested classes and interfaces by updating the source generator to correctly handle types contained within other types. The main change involves updating type name generation to include the containing type's name and adjusting file naming to handle dots in nested type names.

### Key changes
- Updates type name handling to include containing type names with dot notation
- Modifies file name generation to replace dots with underscores for valid file names
- Updates test expectations to reflect the new nested type naming format

---

- *Fixes #28*

### CODE REVIEW

File: Source/Mockerade.SourceGenerators/Internals/SourceGeneration.RegisterMocks.cs [hunk 1]
```diff
@@ -51,7 +51,7 @@ public static string RegisterMocks(ICollection<(string Name, MockClass MockClass
 			}
 			sb.AppendLine(")");
 			sb.Append("\t\t\t{").AppendLine();
-			sb.Append("\t\t\t\t_value = new For").Append(mock.Name).Append(".Mock(constructorParameters, mockBehavior);").AppendLine();
+			sb.Append("\t\t\t\t_value = new For").Append(mock.Name.Replace('.', '_')).Append(".Mock(constructorParameters, mockBehavior);").AppendLine();
```
Comment (vbreuss) [inline Source/Mockerade.SourceGenerators/Internals/SourceGeneration.RegisterMocks.cs:54]: This should not be necessary
